# Generated by Django 2.2 on 2021-09-19 04:34

from django.db import migrations, models
import django.db.models.deletion
import fab_cards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('attack', models.CharField(blank=True, max_length=8, null=True)),
                ('defense', models.CharField(blank=True, max_length=8, null=True)),
                ('resource', models.CharField(blank=True, max_length=8, null=True)),
                ('cost', models.CharField(blank=True, max_length=8, null=True)),
                ('intellect', models.CharField(blank=True, max_length=8, null=True)),
                ('life', models.CharField(blank=True, max_length=8, null=True)),
                ('rarity', models.CharField(blank=True, max_length=2, null=True)),
            ],
            bases=(fab_cards.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
            bases=(fab_cards.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('rarity', models.CharField(blank=True, max_length=2, null=True)),
                ('finish', models.CharField(blank=True, max_length=32, null=True)),
                ('printing_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='fab_cards.Card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='fab_cards.Set')),
            ],
        ),
    ]
