# Generated by Django 4.0.4 on 2022-04-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fab_cards', '0002_printing_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
